Repository wp-cli/cron-command, pull requests merged in 2019-04, with the labels that each got.

#43 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#45 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#46 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  cron-command.php
  phpcs.xml.dist
  src/Cron_Command.php
  src/Cron_Event_Command.php
  src/Cron_Schedule_Command.php
Labels: command:cron, scope:testing

#47 Adapt config anchor to latest template
  features/cron.feature
Labels: bug, scope:testing
